import { Inter } from "next/font/google";
import "./globals.css";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import "../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import Navigation from "./components/layouts/navigation/navigation";

import Import from "./import";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Recpoo",
  description: "Generated by create next app",
};

export const runtime = "edge"

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Import />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
